name: J Ticket
description: Jaebitly 작업 티켓
title: "J-XXX "
labels: ["task"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 내용
      description: 무엇을 하는 작업인지 간단히 작성
      placeholder: 예) 헬스체크 API 추가
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 작업 목록
      description: 필요한 작업을 체크리스트로 작성
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2
    validations:
      required: false

  - type: textarea
    id: done
    attributes:
      label: 완료 조건
      description: 어디까지 되면 끝인지
      placeholder: 예) API가 정상 동작하고 로컬에서 확인 가능
    validations:
      required: false
